# Generated by Django 5.2.5 on 2025-12-26 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_user_table_pincode_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='share_account',
            name='expert',
        ),
        migrations.RemoveField(
            model_name='share_account',
            name='user',
        ),
        migrations.AddField(
            model_name='friend_request',
            name='to_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='fr_tid', to='myapp.user_table'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='share_account',
            name='POST',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.post'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user_table',
            name='status',
            field=models.CharField(default='user', max_length=20),
        ),
        migrations.AlterField(
            model_name='friend_request',
            name='from_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fr_fid', to='myapp.user_table'),
        ),
        migrations.AlterField(
            model_name='imagenotification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user_table'),
        ),
        migrations.CreateModel(
            name='IdentityNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(max_length=200)),
                ('fuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fid', to='myapp.user_table')),
                ('tuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tid', to='myapp.user_table')),
            ],
        ),
    ]
