# Generated by Django 5.2.5 on 2025-12-27 09:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_remove_share_account_expert_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('message', models.CharField(max_length=2000)),
                ('from_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cfrom_id', to='myapp.user_table')),
                ('to_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cto_id', to='myapp.user_table')),
            ],
        ),
    ]
