# Generated by Django 5.2.5 on 2025-12-28 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_chat_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_table',
            name='adhaaer',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
