# Generated by Django 5.2.5 on 2025-12-28 14:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_user_table_adhaaer'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_table',
            name='identity_status',
            field=models.CharField(default='user', max_length=20),
        ),
        migrations.CreateModel(
            name='IdentityTheft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(max_length=200)),
                ('Theft_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tuser', to='myapp.user_table')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nuser', to='myapp.user_table')),
            ],
        ),
    ]
