# Generated by Django 5.2.5 on 2025-12-29 07:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_user_table_identity_status_identitytheft'),
    ]

    operations = [
        migrations.CreateModel(
            name='Share_User_Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(max_length=50)),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_user', to='myapp.user_table')),
                ('share_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='share_user', to='myapp.user_table')),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_user', to='myapp.user_table')),
            ],
        ),
    ]
